<?php if($block->getData('posts')): ?>
	<h2 class='posts'><?php echo $block->escapeHtml($block->getData('posts')); ?></h2>
	<p>This is sample widget. Perform your code here 123.</p>
<?php endif; ?>
<ul class="my-list">
	<li>1st Element</li>
    <li>2nd Element</li>
    <li>3rd Element</li>
    <li>4th Element</li>
    <li>5th Element</li>   
</ul>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".my-list").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 1
            });
        });
    });
</script>